import Head from "next/head";
import Image from "next/image";
import Header from '../components/Header'
import styles from "@/styles/Home.module.css";
import SearchBox from "@/components/Searchbox";
import FetchImages from "@/components/FetchImages";
import Login from "@/components/Login";
import { useEffect, useState } from "react";


export default function Home() {
  const [query,setQuery] = useState('')
  const [isLogin,setIsLogin] = useState(false)
  function updateQuery(query){
    setQuery(query)
  }
  
  function fetchMovies(){
    setQuery('movies')
  }
  function updateLoginStatus(status){
    setIsLogin(status)
    localStorage.setItem("login",status)
  }
  function logOut(){
    setIsLogin(false)
    localStorage.setItem("login",false)
  }
  useEffect(()=>{
    const loginStatus = localStorage.getItem('login')
    setIsLogin(loginStatus)
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
       { !isLogin ? <Login loginCallback={updateLoginStatus}/> :
       <>
         <Header moviesCallback={fetchMovies} signOutCallback={logOut}/>
        <h1>Welcome to Search Application</h1>
        <SearchBox queryCallback={updateQuery}/>
        
        <FetchImages query={query}/>
       </>}
      </div>
    </>
  );
}
